---
title: "Sensitivity Analysis - Detector Edition: Evaluate minimum data to optimize classification performance for Pseudorca vs Other Species using combinations of detectors"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Prediction Steps

## Load libraries, functions, and set directory

```{r, load packages, message=FALSE}

library("easypackages")
libraries("PAMpal", "tidyverse", "banter", "rfPermute", "manipulate", "here", "caret", "future", "foreach", "doFuture", "progressr")
here()

localwd <- here("_R_code")

## functions
source(here('_R_code/filterClicks.r'))

#function to change species Id in banter object
new_sp_id <- function(x, nonPC) {
  for (e in seq_along(x[["events"]][["species"]]) ) {
    if (  x[["events"]][["species"]][[e]] != 33 ) {
      x[["events"]][["species"]][[e]] <- nonPC
    } 
  }
 x 
}

#function to take the log of the signals per detector for plotting purposes
make_log_seq <- function(df, column_name, new_column_name = "Log_Sequence", from = 1, to = length(callsPrd)) {
    unique_vals <- sort(unique(df[[column_name]])) # Get unique values
    log_seq <- log10(callsPrd) # Generatelog values of original sequence
  
  # Create a lookup table and map it to the original values
    lookup <- setNames(log_seq, unique_vals) 
    df[[new_column_name]] <- lookup[as.character(df[[column_name]])]
  
  return(df)
}

#change which detectors are included in data to predict on
select_detectors <- function(bant_lst, detector_nums) {

  # Make a copy of the original list
  new_lst <- bant_lst
  
  # Subset detectors
  new_lst$detectors <- bant_lst$detectors[detector_nums]
  
  return(new_lst)
}

#Set time zone to UTC
Sys.setenv(TZ = 'UTC')
```

## Load banter model

```{r}
bant_model <- readRDS(file.path(localwd, "BanterModel_McCullough2021.rds"))
```

## Load predicton data

```{r}
acstudy_predict <- readRDS(file.path(localwd, 'AcStudy_HI_MI_pred.rds') ) 
# saveRDS(acstudy_predict, file.path(localwd, 'AcStudy_HI_MI_pred.rds') )
# saveRDS(banter_pred, file.path(localwd, 'banter_SA_HI_MI_pred.rds') )
```

## Species codes to exclude from analysis = unidentified dolphins and beaked whales

```{r}
drop_Sp <- c('77','177','277','377','49','59','61','65')
```

## Choose detector combination
```{r}
#Clicks and Whistles Only
# dets <- c(2:5,7,8)
# det_code <- 'ECDW'

#Clicks and Cepstrum Only
# dets <- c(2:6,8)
# det_code <- 'ECCEP'

#Whistles and Cepstrum Only
dets <- c(6,7)
det_code <- 'DWCEP'
```

## Parameters for Predictions
Change detector combination to use
```{r}

#TEST PARAMETERS
# For all detectors
callsMod <- 'All' 
callsPrd <- c(3, 6, 10, 20, 30, 40, 50, 100, 200, 300, 400, 500, 10000, 20000, 30000) 

iters <- c(1:100)

predxn_params <- list(callsMod=callsMod,
                     callsPrd=callsPrd,
                     dets=dets,
                     det_code = det_code,
                     iters=iters,
                     notes = paste0(det_code, ' - Excludes BWs and Unids. - ', Sys.time()) )
                

if (!dir.exists(file.path(localwd,"output"))) {
  dir.create(file.path(localwd,"output"))
}

saveRDS(predxn_params, file.path(localwd, "output", paste0("sens_an_", det_code, "_params.rds")) )

```

## Sensitivity Analysis Loop

```{r}

### START LOOP ####

#save predictions for all iterations of the sensitivity analysis
sens_an_preds_dets <- list()
counter <-1

options(doFuture.rng.onMisuse = "ignore", future.globals.maxSize = 2 * 1024^3)
plan("multisession", workers=7)

tictoc::tic(

for (i in iters){

      # for (call_prd in callsPrd){
    pred_output <- foreach(p = callsPrd,  .options.future = list(packages = c("banter", "randomForest"))) %dofuture% {

    #The variation in results stems from the random selection 
    #of signals from each detector in an encounter.
    acstudy_predict_sub <- sampleDetector(acstudy_predict, n=p)  
    
    # Print Run Info
    cat("***PREDICTIONS***: Iter", i, "For pred calls=", p, ", mod calls=", callsMod, ", and detectors =", dets)
    
    # banter_pred <- export_banter( c(events(acstudy_predict_sub), training=FALSE) )
    banter_pred <- export_banter(acstudy_predict_sub, training=FALSE, dropSpecies = drop_Sp) 
    
    ## Make a dataframe with event IDs and original species codes
    origSpCodes <- data.frame(banter_pred[["events"]])
    
    ## Change 'other' species code to 577
    banter_pred <- new_sp_id(banter_pred, "577")
    
 
    ### CLICK DETECTOR FILTERS ####
    # Ensure that detector numbers, d, match the order in the banter object
    
    for(d in c(1,2,3,4,5,8)){  
      banter_pred$detectors[[d]]<-filter(banter_pred$detectors[[d]],BW_10dB > 5)
      banter_pred$detectors[[d]]<-filter(banter_pred$detectors[[d]],peak > 5 & peak < 80)
      banter_pred$detectors[[d]]<-filter(banter_pred$detectors[[d]],duration > 2 & duration < 1000)
    }
    
    # Remove clicks in individual detectors
    banter_pred$detectors$Click_Detector_1<-filter(banter_pred$detectors$Click_Detector_1, peak>2 & peak<15)
    banter_pred$detectors$Click_Detector_2<-filter(banter_pred$detectors$Click_Detector_2, peak>15 & peak<30)
    banter_pred$detectors$Click_Detector_3<-filter(banter_pred$detectors$Click_Detector_3, peak>30 & peak<50)
    banter_pred$detectors$Click_Detector_4<-filter(banter_pred$detectors$Click_Detector_4, peak>30 & peak<50)
    banter_pred$detectors$Click_Detector_5<-filter(banter_pred$detectors$Click_Detector_5, peak>50 & peak<80) 
  
    
   ## Select subset of detectors
   banter_pred_sub <- select_detectors(banter_pred, dets)      
    
    ## Apply model, get predictions, make a dataframe to compare to true event IDs to predictions
    
    pred_results <- banter::predict(bant_model, banter_pred_sub)
    
    pred_resultsDF <- as.data.frame(pred_results[["predict.df"]])
    
    pred_resultsDF <- pred_resultsDF[, c(1, 5, 2:4,6)]
    
    pred_resultsDF <- inner_join(origSpCodes, pred_resultsDF, by = 'event.id')
    
    pred_resultsDF$iter = i
    pred_resultsDF$tot_sigp = p
    pred_resultsDF$tot_sigm = callsMod
    pred_resultsDF$dets = paste(dets, collapse = "")
    
all_levels <- union(levels(factor(pred_resultsDF$predicted)),
                    levels(factor(pred_resultsDF$original)))
pred_resultsDF$predicted <- factor(pred_resultsDF$predicted, levels = all_levels)
pred_resultsDF$original  <- factor(pred_resultsDF$original,  levels = all_levels)   


## SAVE confusion matrices in a list

## This works, but EC/CEP still doesn't predict 33 correctly   
    # confMat <- safe_confusionMatrix(pred_resultsDF$predicted, pred_resultsDF$original)
 
confMat <- confusionMatrix(factor(pred_resultsDF$predicted), factor(pred_resultsDF$original), mode = 'everything')

    # if (all(dets != 7)) { 
    #  confMatscore <-data.frame(overall=confMat[["overall"]][[1]],
    #                  true33 = confMat[["table"]][4],
    #                  false33 = confMat[["table"]][3],
    #                  false577 = confMat[["table"]][2],
    #                  true577 = confMat[["table"]][1],
    #                  iter = i,
    #                  tot_sigp = p,
    #                  tot_sigm = callsMod) 
    #   
    #   } else {
    
     confMatscore <-data.frame(overall=confMat[["overall"]][[1]],
                     true33 = confMat[["table"]][1],
                     false33 = confMat[["table"]][2],
                     false577 = confMat[["table"]][3],
                     true577 = confMat[["table"]][4],
                     iter = i,
                     tot_sigp = p,
                     tot_sigm = callsMod)
      #} 
 
 return(list(
   pred_results = pred_resultsDF, 
   confmat_score = confMatscore))

 } # callsPrd
    
 ## save prediction results
    sens_an_preds_dets[[counter]] <- pred_output
     counter <- counter + 1 
    
  } #iteration
)
plan("sequential")

tictoc::toc()

## Save predictions from sensitivity analysis
saveRDS(sens_an_preds_dets, file= file.path(localwd, 'output', paste0('sens_an_', det_code, '_results.rds') ) )


```


## Plot Setup

```{r}

## Pull out scores from each iteration
data2plot <- data.frame()

for (y in (1:length(iters)) ){ 
  for (k in (1:length(callsPrd))) {
  
  tmp <-sens_an_preds_dets[[y]][[k]][["confmat_score"]]
   
  data2plot <- rbind(data2plot, tmp)
  }
}


## Assign log values to original values of 'signals per detector'
df <- data.frame(tot_sigp = callsPrd, times = 100)

data2plot2 <- make_log_seq(data2plot, "tot_sigp", "trans_sigp")
head(data2plot2)

data2plot <- data2plot2


```

## Plot Prediction Results

```{r}

# cols =  c("#214DBEFF" ,"#51B4FDFF" ,"#00E3DDFF" ,"#00F293FF" ,"#C6FC3FFF","#FF9B00", "#FF479A")


results_scorep <- data2plot %>% group_by(tot_sigp, trans_sigp) %>%
                        summarise(mean = mean(overall),
                                sd = sd(overall),
                                mean_mis = mean(false33),
                                sd_mis = sd(false33))# %>% arrange(as.numeric(iter))


pred_plot = ggplot(data = results_scorep, aes(x = trans_sigp, y = mean)) +
  geom_line(lwd = .75) +
  geom_point(size=2) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width = .07, linewidth = 0.5) +
  labs(title = paste0("BANTER Predictions: Pc vs Other - ", det_code, ",", iters[length(iters)], " iterations total") , 
       subtitle = "Model: excludes BWs & Unids, trees = 2000 & 20000, sampsize = 15", 
       x = "Signals per Detector",
       y = "Mean Overall Accuracy",
       color = "Score Type") +

scale_x_continuous(breaks = data2plot$trans_sigp,
labels = data2plot$tot_sigp)  +
    scale_y_continuous(breaks = pretty(data2plot$overall, n=5)) +
  theme_bw() +
  theme(plot.title = element_text(size = 18, face = "bold"),
        plot.subtitle = element_text(size=13),
        axis.title.y = element_text(size = 16, margin= margin(r=10)),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 10, angle = 50, vjust = 0.8),
        axis.ticks.length=unit(.25, "cm"),
        panel.grid.minor = element_line(color = "white", linewidth  = 0.5,
                                        linetype = "dotted"))
   
pred_plot
```

## Save Plot
```{r}
ggsave( file= file.path(localwd, 'output', paste0('sens_an_', det_code, '.png') ), plot = pred_plot, width = 10, height = 6, dpi = 300 ) 

```
