---
title: "Sensitivity Analysis: Evaluate minimum data to optimize classification performance for Pseudorca vs Other Species"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Prediction Steps

## Load libraries and set directory

```{r, load packages, message=FALSE}

library("easypackages")
libraries("PAMpal", "tidyverse", "banter", "rfPermute", "manipulate", "here", "caret", "future", "foreach", "doFuture", "progressr")
here()

localwd <- here("_R_code","sens_an")

## functions
source(here('_R_code/filterClicks.r'))

#function to change species Id in banter object
new_sp_id <- function(x, nonPC) {
  for (e in seq_along(x[["events"]][["species"]]) ) {
    if (  x[["events"]][["species"]][[e]] != 33 ) {
      x[["events"]][["species"]][[e]] <- nonPC
    } 
  }
 x 
}

#function to take the log of the signals per detector for plotting purposes
make_log_seq <- function(df, column_name, new_column_name = "Log_Sequence", from = 1, to = length(callsPrd)) {
    unique_vals <- sort(unique(df[[column_name]])) # Get unique values
    log_seq <- log10(callsPrd) # Generatelog values of original sequence
  
  # Create a lookup table and map it to the original values
    lookup <- setNames(log_seq, unique_vals) 
    df[[new_column_name]] <- lookup[as.character(df[[column_name]])]
  
  return(df)
}



#Set time zone to UTC
Sys.setenv(TZ = 'UTC')
```

## Load banter model

```{r}
bant_model <- readRDS(file.path(localwd, "BanterModel_McCullough2021.rds"))
```

## Load predicton data

```{r}
acstudy_predict <- readRDS(file.path(localwd, 'AcStudy_HI_MI_pred.rds') ) 

```

## Sets pecies codes to exclude, or drop, from analysis - unidentified dolphins and beaked whales

```{r}
drop_Sp <- c('77','177','277','377','49','59','61','65')
```

## Parameters for Predictions

```{r}

#TEST PARAMETERS
# For all detectors
callsMod <- 'All' 
callsPrd <- c(3, 6, 10, 20, 30, 40, 50, 100, 200, 300, 400, 500, 10000, 20000, 30000) 

dets <- c(2:8)

iters <- c(1:100)

predxn_params <- list(callsMod=callsMod,
                     callsPrd=callsPrd,
                     dets=dets,
                     iters=iters,
                     notes = 'FULL MODEL. Excludes BWs and Unids. All detectors. 17 events. Filtered clicks!')
                

if (!dir.exists(file.path(localwd,"output"))) {
  dir.create(file.path(localwd,"output"))
}

saveRDS(predxn_params, file.path(localwd, "output", "sens_an_pred_params.rds"))

```

## Sensitivity Analysis Loop

```{r}

### START LOOP ####

#save predictions for all iterations of the sensitivity analysis
sens_an_preds <- list()
counter <-1

options(doFuture.rng.onMisuse = "ignore", future.globals.maxSize = 2 * 1024^3)
plan("multisession", workers=7)

tictoc::tic(

for (i in iters){

      # for (call_prd in callsPrd){
    pred_output <- foreach(p = callsPrd,  .options.future = list(packages = c("banter", "randomForest"))) %dofuture% {

    #The variation in results stems from the random selection 
    #of signals from each detector in an encounter.
    acstudy_predict_sub <- sampleDetector(acstudy_predict, n=p)  
    
    # Print Run Info
    cat("***PREDICTIONS***: Iter", i, "For pred calls=", p, ", mod calls=", callsMod, ", and detectors =", dets)
    
    # banter_pred <- export_banter( c(events(acstudy_predict_sub), training=FALSE) )
    banter_pred <- export_banter(acstudy_predict_sub, training=FALSE, dropSpecies = drop_Sp) 
    
    ## Make a dataframe with event IDs and original species codes
    origSpCodes <- data.frame(banter_pred[["events"]])
    
    ## Change 'other' species code to 577
    banter_pred <- new_sp_id(banter_pred, "577")
    
    ### CLICK DETECTOR FILTERS ####
    #Remove clicks with bandwidth at 10dB < 5 kHz (Load 'dplyr' package)
    for(d in c(1,2,3,4,5,8)){  #ensure that detector numbers match here
      banter_pred$detectors[[d]]<-filter(banter_pred$detectors[[d]],BW_10dB > 5)
      banter_pred$detectors[[d]]<-filter(banter_pred$detectors[[d]],peak > 5 & peak < 80)
      banter_pred$detectors[[d]]<-filter(banter_pred$detectors[[d]],duration > 2 & duration < 1000)
    }
    
    #Remove clicks in individual detectors
    banter_pred$detectors$Click_Detector_1<-filter(banter_pred$detectors$Click_Detector_1, peak>2 & peak<15)
    banter_pred$detectors$Click_Detector_2<-filter(banter_pred$detectors$Click_Detector_2, peak>15 & peak<30)
    banter_pred$detectors$Click_Detector_3<-filter(banter_pred$detectors$Click_Detector_3, peak>30 & peak<50)
    banter_pred$detectors$Click_Detector_4<-filter(banter_pred$detectors$Click_Detector_4, peak>30 & peak<50)
    banter_pred$detectors$Click_Detector_5<-filter(banter_pred$detectors$Click_Detector_5, peak>50 & peak<80) 
    
    
    ## Apply model, get predictions, make a dataframe to compare to true event IDs to predictions
    
    pred_results <- banter::predict(bant_model, banter_pred)
    
    pred_resultsDF <- as.data.frame(pred_results[["predict.df"]])
    
    pred_resultsDF <- pred_resultsDF[, c(1, 5, 2:4,6)]
    
    pred_resultsDF <- inner_join(origSpCodes, pred_resultsDF, by = 'event.id')
    
    pred_resultsDF$iter = i
    pred_resultsDF$tot_sigp = p
    pred_resultsDF$tot_sigm = callsMod
    pred_resultsDF$dets = paste(dets, collapse = "")
    
   # return(pred_resultsDF)
   
#     predxns <- predictions(acstudy_predict, callsPrd, callsMod, bant_model, i, dets)
# 
# # SAVE list of dataframes with prediction results to look at misclassifieds later
#   for(h in 1:length(predxns[["bantpred_resultsi"]])){
#     bantpred_results[[length(bantpred_results) + 1]] <- predxns[["bantpred_resultsi"]][[h]]


##  MEMORY saving stuff 
# rm( AcStudy_PcUO_sub, banter_mod)
# gc()

# SAVE confusion matrices in a list

# for(h in 1:length(predxns[["bantpred_confMati"]])){
# bantpred_confmatAll[[length(bantpred_confmatAll) + 1]] <- predxns[["bantpred_confMati"]][[h]]
# }#c(confmat = confMat, dets= paste(dets, collapse = ""), iter=i, tot_signals = call_prd)
# 
# # Save confusion matrix overall scores for plotting
# bantpred_confmatScores[[length(bantpred_confmatScores) + 1]] <- predxns[["bantpred_confMatScoresi"]]


 confMat <- confusionMatrix(factor(pred_resultsDF$predicted),factor(pred_resultsDF$original ), mode = 'everything')

 confMatscore <-data.frame(overall=confMat[["overall"]][[1]],
                     true33 = confMat[["table"]][1],
                     false33 = confMat[["table"]][2],
                     false577 = confMat[["table"]][3],
                     true577 = confMat[["table"]][4],
                     iter = i,
                     tot_sigp = p,
                     tot_sigm = callsMod)
 return(list(
   pred_results = pred_resultsDF, 
   confmat_score = confMatscore))

 } # callsPrd
    
 ## save prediction results
    sens_an_preds[[counter]] <- pred_output
     counter <- counter + 1 
    
  } #iteration
)
plan("sequential")

tictoc::toc()
```

## Save predictions from sensitivity analysis

```{r}

saveRDS(sens_an_preds, file= file.path(localwd, 'output', 'sens_an_results.rds') )

```

## Plot predictions

```{r}

## Pull out scores from each iteration
data2plot <- data.frame()

for (y in (1:length(iters)) ){ 
  for (k in (1:length(callsPrd))) {
  
  tmp <-sens_an_preds[[y]][[k]][["confmat_score"]]
   
  data2plot <- rbind(data2plot, tmp)
  }
}


## Assign log values to original values of 'signals per detector'
df <- data.frame(tot_sigp = callsPrd, times = 100)

data2plot2 <- make_log_seq(data2plot, "tot_sigp", "trans_sigp")
head(data2plot2)

data2plot <- data2plot2


```

## Plot Prediction Results

```{r}

cols =  c("#214DBEFF" ,"#51B4FDFF" ,"#00E3DDFF" ,"#00F293FF" ,"#C6FC3FFF","#FF9B00", "#FF479A")


results_scorep <- data2plot %>% group_by(tot_sigp, trans_sigp) %>%
                        summarise(mean = mean(overall),
                                sd = sd(overall),
                                mean_mis = mean(false33),
                                sd_mis = sd(false33))# %>% arrange(as.numeric(iter))


p = ggplot(data = results_scorep, aes(x = trans_sigp, y = mean)) +
  geom_line(lwd = .75) +
  geom_point(size=2) +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width = .07, linewidth = 0.5) +
  labs(title = paste0("BANTER Predictions: Pc vs Other - Full Model, ", iters[length(iters)], " iterations total") , # Clicks Only
       subtitle = paste0("Model: excludes BWs & Unids,", " trees=2000", " & ", 20000, ", sampsize = 15"), # ':', n_evt[length(n_evt)] ) ,
       x = "Signals per Detector",
       y = "Mean Overall Accuracy",
       color = "Score Type") +

scale_x_continuous(breaks = data2plot$trans_sigp,
labels = data2plot$tot_sigp)  +
    scale_y_continuous(breaks = pretty(data2plot$overall, n=5)) +
  theme_bw() +
  theme(plot.title = element_text(size = 18, face = "bold"),
        plot.subtitle = element_text(size=13),
        axis.title.y = element_text(size = 16, margin= margin(r=10)),
        axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 10, angle = 50, vjust = 0.8),
        axis.ticks.length=unit(.25, "cm"),
        panel.grid.minor = element_line(color = "white", linewidth  = 0.5,
                                        linetype = "dotted"))
   
p


## Save Plot
ggsave( file= file.path(localwd, 'output', 'sens_an_pred.png'), plot = p, width = 10, height = 6, dpi = 300 ) 

```
