---
title: "Precision-Recall Curves"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---


```{r}
library(PRROC)
library(tidyverse)


```

# 1. Load the classification results of sensitivity analysis (large list)
```{r}
# Change det_combo to 1 and det_code accordingly if plotting results from different detector combinations
det_combo <- 0
det_code <- 'DWCEP' #'ECCEP' 'ECDW'

if (det_combo == 0){
sa_results <- readRDS(file.path('output', 'sens_an_results.rds'))
sa_params <- readRDS(file.path('output', 'sens_an_pred_params.rds'))
} else {
sa_results <- readRDS(file.path('output', paste0('sens_an_', det_code, '_results.rds')) )
sa_params <- readRDS(file.path('output', paste0('sens_an_', det_code, '_params.rds')) )
}

```


# 2. Make Precision-Recall dataframe 
```{r}
data2plot_pr <- data.frame()

for (y in (1:length(sa_params[["iters"]])) ){ 
  for (z in (1:length(sa_params[["callsPrd"]]))) {
    
# Get true binary labels    
true_labels <- factor(sa_results[[y]][[z]][["pred_results"]][["original"]], levels= c("X33", "X577")) 

# Calculate prevalence ( proportion of the total population that belongs to the positive class, FKWs )
prevalence = sum(true_labels=='X33')/ (sum(true_labels=='X33') +sum(true_labels=='X577'))

# Get model-predicted probabilities for "X33" (positive class)
prob_33 <- sa_results[[y]][[z]][["pred_results"]][["X33"]] 

# Create the PR curve
pr_obj <- pr.curve(scores.class0 = prob_33[true_labels == "X33"],
                   scores.class1 = prob_33[true_labels == "X577"],
                   curve = TRUE)

pr_data <- data.frame(iter = y,
                      tot_sigp = sa_params[["callsPrd"]][z],
                      Recall = pr_obj$curve[,1],
                      Precision = pr_obj$curve[,2],
                      Threshold = pr_obj$curve[,3],
                      AUPRC = pr_obj$auc.integral,
                      prev = prevalence) %>% filter(Recall > 0)


data2plot_pr <- rbind(data2plot_pr, pr_data)
  }
}

```

# 3. Calculate average P-R curves for total signals
```{r}
# Define common recall points for interpolating the mean curves
recall_points <- seq(0, 1, length.out = 100)

# Calculate the mean curve coordinates per tot_sigp
averaged_pr_curves <- data2plot_pr %>%
  # Group by the model to perform interpolation separately
  group_by(tot_sigp, iter) %>%
  do({
    # Interpolate Precision values at common Recall points
    approx_precision <- approx(.$Recall, .$Precision, xout = recall_points, rule = 2)
    data.frame(Recall = approx_precision$x, Precision = approx_precision$y, Model = unique(.$tot_sigp))
  }) %>%
  ungroup() %>%
  # Now group by the common Recall points and find the mean Precision across models
  group_by(tot_sigp, Recall) %>%
  summarise(Mean_Precision = mean(Precision, na.rm = TRUE), .groups = 'drop')

```

## 3b. Calculate F1-Score
```{r}
averaged_pr_curves$f1 <- 2 * averaged_pr_curves$Mean_Precision * averaged_pr_curves$Recall / (averaged_pr_curves$Mean_Precision+averaged_pr_curves$Recall)

f1_pt <- averaged_pr_curves[which.max(averaged_pr_curves$f1), ] 
```



# 4. Plot all P-R curves
```{r}
multi_pr_plot <- ggplot(data2plot_pr, aes(x = Recall, y = Precision)) +
  
  # Plot individual model curves (colored by total signals)
  # interaction() prevents sawtooth, ensures that the correct points are connected between both factors
  geom_line(aes(color = as.factor(tot_sigp), group = interaction(tot_sigp, iter)), 
            linewidth = 0.8, alpha = 0.8) +
  
  # Plot the averaged curve (bold and black)
  geom_line(data = averaged_pr_curves,
            aes(y = Mean_Precision, group = as.factor(tot_sigp)),
            color = 'red', #as.factor(tot_sigp)),
            linewidth = 0.75, linetype = "dashed") +
  # Add baseline prevalence line
  geom_hline(yintercept = mean(data2plot_pr$prev), linetype = "dotted", linewidth=1.2, color = "darkgray") +
  
  labs(title = "Precision-Recall Curves (with Averaged Curves)",
       subtitle = paste("Includes", length(iters), "runs. Baseline Prevalence:", round(prevalence,3) ),
       x = "Recall (Sensitivity)",
       y = "Precision",
       color = "Signals per Detector") +
  scale_colour_viridis_d() +
  # scale_color_manual(values = c("Model A" = "#0072B2", "Model B" = "#D55E00")) +
  theme_bw() +
  coord_fixed() +
  xlim(0, 1) + ylim(0, 1)

multi_pr_plot
```

## Save Plot
```{r}
if (det_combo == 0){
ggsave( file= file.path('output', paste0('prec_rec_all.png') ), plot = multi_pr_plot, width = 10, height = 6, dpi = 300 ) 
} else {
ggsave( file= file.path('output', paste0('prec_rec_all_', det_code, '.png') ), plot = multi_pr_plot, width = 10, height = 6, dpi = 300 ) 
}

```


# 5. Plot mean P-R curves
```{r}
multi_pr_plot_mean <- ggplot(data2plot_pr, aes(x = Recall, y = Precision)) +
  
  # Plot individual model curves (colored by total signals)
  # interaction() prevents sawtooth, ensures that the correct points are connected between both factors
  # geom_line(aes(color = as.factor(tot_sigp), group = interaction(tot_sigp, iter)), 
  #           linewidth = 0.8, alpha = 0.8) +
  
  # Plot the averaged curve (bold and black)
  geom_line(data = averaged_pr_curves,
            aes(y = Mean_Precision, group = as.factor(tot_sigp),
            color = as.factor(tot_sigp)),
            linewidth = 1) +
  # Add baseline prevalence line
  geom_hline(yintercept = mean(data2plot_pr$prev), linetype = "dotted", linewidth=1.2, color = "darkgray") +
  
  # geom_point(x=f1_pt$Recall, y=f1_pt$Mean_Precision) +
  
  labs(title = "Mean Precision-Recall Curves",
       subtitle = paste("Includes", length(iters), "runs. Baseline Prevalence:", round(prevalence,3) ),
       x = "Recall (Sensitivity)",
       y = "Precision",
       color = "Signals per Detector") +
  scale_colour_viridis_d() +
  # scale_color_manual(values = c("Model A" = "#0072B2", "Model B" = "#D55E00")) +
  theme_bw() +
  coord_fixed() +
  xlim(0, 1) + ylim(0, 1)

multi_pr_plot_mean
```

## Save Plot
```{r}
if (det_combo == 0){
ggsave( file= file.path('output', paste0('prec_rec_means_', Sys.Date() , '.png') ), plot = multi_pr_plot_mean, width = 10, height = 6, dpi = 300 ) 
} else {
ggsave( file= file.path('output', paste0('prec_rec_means_', det_code, '.png') ), plot = multi_pr_plot_mean, width = 10, height = 6, dpi = 300 ) 
}

```

# 6. Find Optimal Threshold
```{r}
target_recall <- 0.75
target_precision <- 0.80


# 3. CALCULATE DISTANCE TO TARGET
# We calculate the Euclidean distance (d = sqrt((P_actual - P_target)^2 + (R_actual - R_target)^2))
# The point with the smallest distance is the closest match to the target.
data2plot_pr <- data2plot_pr %>%
  mutate(
    # Calculate the squared difference from the target for both metrics
    distance_sq = (Precision - target_precision)^2 + (Recall - target_recall)^2
  ) 

# 4. FIND THE OPTIMAL THRESHOLD
optimal_row <- data2plot_pr %>%
  arrange(distance_sq) %>% head(1)

# Get the coordinates of the optimal point on the average curve
optimal_avg_point <- averaged_pr_curves %>%
    mutate(
    # Calculate the squared difference from the target for both metrics
    distance_sq = (Mean_Precision - target_precision)^2 + (Recall - target_recall)^2
  ) %>% arrange(distance_sq) %>% head(1)


```

# 7. Work with Medians to Evaluate Performance
```{r}
# 1. LOAD COUNT DATA FOR PREDICTION TEST DATA

sig_count <- read.csv(file.path('output', 'CountsSApreds_20251010.csv'))

# 2. CALCULATE MEDIANS PER COLUMN
# Calculate the median for each column 
median_data <- sig_count %>%
  # Reshape the data to long format first to easily group and calculate medians
  pivot_longer(cols = c('NCep', 'NClicks', 'NWhistle', 'TS'), names_to = "Variable", values_to = "Value") %>%
  group_by(Variable) %>%
  summarise(
    Mean = mean(Value, na.rm = TRUE),
    Median = median(Value, na.rm = TRUE),
    IQR = IQR(Value, na.rm = TRUE), #spread of central 50%, distance btwn Q1 and Q3
    Q1 = quantile(Value, 0.25, na.rm = TRUE),
    Q3 = quantile(Value, 0.75, na.rm = TRUE)
  
    )

# 3. RESHAPE DATA FROM WIDE TO LONG FORMAT

df_long <- sig_count %>%
  pivot_longer(
    cols = c('NCep', 'NClicks', 'NWhistle', 'TS'), # Apply to all columns
    names_to = "Variable", # Column names become this new column's values
    values_to = "Value"    # The actual data points go here
  )
# Join Q3 limits to the long data and filter
df_visual <- df_long %>%
  left_join(median_data %>% select(Variable, Q3), by = "Variable") %>%
  filter(Value <= Q3)
```

```{r}
# 4. GENERATE THE PLOT
ggplot(df_visual, aes(x = Value)) +
  
  # A. Create the Histograms
  geom_histogram(
    bins = 20, # Adjust bin count for better visualization
    fill = "skyblue", 
    color = "black", 
    alpha = 0.7
  ) +
  
  # B. Draw the Median Line
  geom_vline(
    data = median_data, 
    aes(xintercept = Median),
    linetype = "dashed", 
    color = "red", 
    linewidth = .8
  ) +
  
  # C. Facet the plot by the 'Variable' column
  facet_wrap(~ Variable, scales = "free_x") + 
  
  labs(
    title = "Distribution and Median of Signals Types:",
    subtitle = "Prediction Test Data Set",
    x = "Value",
    y = "Frequency"
  ) +
  theme_minimal(base_size = 14)
```

```{r}

```

